comment: false
ignore:
  - "**/*.freezed.dart"
  - "**/*.g.dart"
  - "**/*.mocks.dart"
  - "**/l10n/*.dart"

coverage:
  precision: 2
  round: down
  range: 80...100
  status:
    project:
      default:
        threshold: 5%
    patch: off
