name: ubuntu_desktop_provision

packages:
  - apps/**
  - packages/**

command:
  bootstrap:
    enforceLockfile: true
    runPubGetInParallel: false
    environment:
      sdk: ">=3.0.0 <4.0.0"
      flutter: ">=3.32.1"

    dependencies:
      args: ^2.4.2
      async: ^2.11.0
      collection: ^1.17.0
      crypt: ^4.3.1
      dbus: ^0.7.10
      diacritic: ^0.1.5
      ffi: ^2.1.0
      file: ^7.0.0
      flutter_html: ^3.0.0-beta.2
      flutter_riverpod: ^2.5.1
      flutter_spinbox: ^0.13.1
      flutter_svg: ^2.0.10
      form_field_validator: ^1.1.0
      freezed_annotation: ^2.4.1
      grpc: ^4.0.1
      gsettings: ^0.2.8
      handy_window: ^0.4.0
      intl: ^0.20.2
      json_annotation: ^4.9.0
      meta: ^1.11.0
      nm: ^0.5.0
      package_config: ^2.1.0
      path: ^1.8.3
      platform: ^3.1.2
      safe_change_notifier: ^0.4.0
      scroll_to_index: ^3.0.1
      split_view: ^3.2.1
      stdlibc: ^0.1.4
      ubuntu_flavor: ^0.4.0
      ubuntu_localizations: ^0.5.2+2
      ubuntu_logger: ^0.1.1
      ubuntu_service: ^0.3.1
      ubuntu_session: ^0.0.4
      ubuntu_widgets: ^0.7.3
      udev: ^0.0.3
      upower: ^0.7.0
      url_launcher: ^6.2.5
      wizard_router: ^1.2.0
      xdg_directories: ^1.0.4
      xdg_locale: ^0.0.1
      yaml: ^3.1.2
      yaru: ^8.1.0
      yaru_window: ^0.2.1

    dev_dependencies:
      build_runner: ^2.4.8
      fake_async: ^1.3.1
      ffigen: ^11.0.0
      freezed: ^2.4.6
      json_serializable: ^6.7.1
      mockito: 5.4.4
      plugin_platform_interface: ^2.1.8
      test: any
      ubuntu_lints: ^0.4.0
      ubuntu_test: ^0.2.2
      url_launcher_platform_interface: ^2.3.2
      yaru_test: ^0.3.0

scripts:
  # collect coverage information for all packages
  coverage: >
    melos exec -c 1 --fail-fast --dir-exists=test -- \
      flutter test --coverage && melos run coverage:cleanup

  # cleanup generated files from coverage
  coverage:cleanup: >
    melos exec --file-exists=coverage/lcov.info -- \
      lcov --remove coverage/lcov.info \
        '**/*.freezed.dart' \
        '**/*.g.dart' \
        '**/*.mocks.dart' \
        '**/l10n/*.dart' \
        '**/*.pb*.dart' \
        --ignore-errors unused \
        -o coverage/lcov.info

  # format all packages' files except for generated files
  format:exclude: >
    melos exec -c 1 -- \
      "find $MELOS_PACKAGE_PATH -name '*.dart' \
          ! -name '*.freezed.dart' \
          ! -name '*.g.dart' \
          ! -name '*.mocks.dart' \
          ! -path '*/l10n/*' \
          ! -name '*.pb*.dart' \
          ! -path '*/.*/*' \
          | xargs dart format --set-exit-if-changed"

  # run build_runner to generate code in all packages
  generate: >
    melos exec -c 1 --fail-fast --depends-on="build_runner" -- \
      dart run build_runner build --delete-conflicting-outputs

  # run gen-l10n to generate localizations in all packages
  gen-l10n: >
    melos exec -c 1 --fail-fast --file-exists="lib/l10n.dart" -- \
     flutter gen-l10n

  # remove unused translations in all packages, you have to have jq installed.
  clean-l10n: >
    melos exec --depends-on="translations_cleaner" -c 1 -- \
      dart run translations_cleaner clean-translations && \
      find . -name "*.arb" -exec sh -c 'jq . --indent 2 {} > temp.json && mv temp.json {}' \;

  # run integration tests in all packages
  integration_test: >
    melos exec -c 1 --fail-fast --dir-exists=integration_test -- \
      flutter test integration_test

  # runs "flutter pub <arg(s)>" in all packages
  pub: melos exec -c 1 -- flutter pub "$@"

  # run tests in all packages
  test: >
    melos exec -c 1 --fail-fast --dir-exists=test -- \
      flutter test

  # run pub upgrade in all packages
  upgrade: melos exec -c 1 flutter pub upgrade

  protoc:
    run: |
      rm -rf ./packages/provd_client/lib/src/generated/* ./packages/landscape_stubs/lib/src/generated/* &&
      protoc --dart_out=grpc:./packages/provd_client/lib/src/generated \
        -I./provd/protos ./provd/protos/*.proto google/protobuf/empty.proto google/protobuf/wrappers.proto &&
      protoc --dart_out=grpc:./packages/landscape_stubs/lib/src/generated \
        -I./packages/landscape_stubs/protos ./packages/landscape_stubs/protos/*.proto google/protobuf/timestamp.proto google/protobuf/empty.proto
