#!/bin/bash
TARGET=/target

set -eux

(
cat << 'EOF'
#!/bin/bash
LATEST=$(wget -qO- https://raw.githubusercontent.com/d-loose/provision-testing/main/ubuntu-desktop-init_latest.snap)
wget "https://github.com/d-loose/provision-testing/raw/main/$LATEST" -O ubuntu-desktop-init_latest.snap
snap install --dangerous --devmode ubuntu-desktop-init_latest.snap
EOF
) > $TARGET/usr/bin/install-ubuntu-init
chmod +x $TARGET/usr/bin/install-ubuntu-init

(
cat << 'EOF'
[Unit]
Description=Installs ubuntu-desktop-init snap
After=network-online.target snapd.seeded.service
Before=display-manager.service

[Service]
ExecStart=/usr/bin/install-ubuntu-init
Type=oneshot
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
EOF
) > $TARGET/etc/systemd/system/install-ubuntu-init.service
ln -s /etc/systemd/system/install-ubuntu-init.service $TARGET/etc/systemd/system/multi-user.target.wants/

sed -i 's|/usr/libexec/gnome-initial-setup|env LOG_FILE=/tmp/init.log LOG_LEVEL=debug /snap/ubuntu-desktop-init/current/bin/ubuntu_init|' $TARGET/usr/share/applications/gnome-initial-setup.desktop