arb-dir: lib/l10n
template-arb-file: factory_reset_tools_en.arb
output-class: FactoryResetToolsLocalizations
output-localization-file: factory_reset_tools_localizations.dart
synthetic-package: false
nullable-getter: false
