name: UI bug report for Ubuntu Desktop Provision
description: Create a report to help us improve
labels:
  - bug
assignees:
  - d-loose
  - sminez
  - matthew-hagemann
body:
- type: markdown
  attributes:
    value: |
      :note: This repository houses the Flutter UI used by the Ubuntu Installer. If your issue involves backend functionality, please report it under the Subiquity project here: [https://bugs.launchpad.net/ubuntu/+source/subiquity](https://bugs.launchpad.net/ubuntu/+source/subiquity).
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: |
      Please search to see if an issue already exists for this feature: https://github.com/canonical/ubuntu-desktop-provision/issues.
    options:
    - label: I have searched the existing issues
      required: true
- type: textarea
  attributes:
    label: Describe the bug
    description: |
      A clear and concise description of what the bug is. You can also attach screenshots or recordings.
  validations:
    required: false
- type: textarea
  attributes:
    label: Steps to reproduce the behavior
    placeholder: |
      1. Go to '...'
      2. Click on '....'
      3. Scroll down to '....'
      4. See error
  validations:
    required: false
- type: textarea
  id: expected_behavior
  attributes:
    label: Expected behavior
    description: |
      A clear and concise description of what you expected to happen.
  validations:
    required: false
- type: dropdown
  attributes:
    label: Ubuntu release
    description: What version of our Ubuntu are you running?
    options:
      - '24.10'
      - 24.04 LTS
      - Other (specify in the last field)
  validations:
    required: false
- type: dropdown
  attributes:
    label: What architecture are you using?
    multiple: false
    options:
      - amd64
      - arm64
      - Other (specify in the last field)
      - I don't know
  validations:
    required: false
- type: textarea
  attributes:
    label: System info
    description: |
      Please run this command in your terminal:
      ```uname -rv && snap info ubuntu-desktop-bootstrap```
      and paste the output here. It will give us information about your system such as the kernel version and the versions of the relevant packages.
  validations:
    required: false
- type: textarea
  attributes:
    label: Additional context
    description: |
      You can attach screenshots, recordings, logs, or any other information that you think might be helpful. Please remember to anonymize any personal data.
  validations:
    required: false

