// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.2
// source: protos/ad.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AdDomainNameValidation int32

const (
	AdDomainNameValidation_OK              AdDomainNameValidation = 0
	AdDomainNameValidation_EMPTY           AdDomainNameValidation = 1
	AdDomainNameValidation_TOO_LONG        AdDomainNameValidation = 2
	AdDomainNameValidation_INVALID_CHARS   AdDomainNameValidation = 3
	AdDomainNameValidation_START_DOT       AdDomainNameValidation = 4
	AdDomainNameValidation_END_DOT         AdDomainNameValidation = 5
	AdDomainNameValidation_START_HYPHEN    AdDomainNameValidation = 6
	AdDomainNameValidation_END_HYPHEN      AdDomainNameValidation = 7
	AdDomainNameValidation_MULTIPLE_DOTS   AdDomainNameValidation = 8
	AdDomainNameValidation_REALM_NOT_FOUND AdDomainNameValidation = 9
)

// Enum value maps for AdDomainNameValidation.
var (
	AdDomainNameValidation_name = map[int32]string{
		0: "OK",
		1: "EMPTY",
		2: "TOO_LONG",
		3: "INVALID_CHARS",
		4: "START_DOT",
		5: "END_DOT",
		6: "START_HYPHEN",
		7: "END_HYPHEN",
		8: "MULTIPLE_DOTS",
		9: "REALM_NOT_FOUND",
	}
	AdDomainNameValidation_value = map[string]int32{
		"OK":              0,
		"EMPTY":           1,
		"TOO_LONG":        2,
		"INVALID_CHARS":   3,
		"START_DOT":       4,
		"END_DOT":         5,
		"START_HYPHEN":    6,
		"END_HYPHEN":      7,
		"MULTIPLE_DOTS":   8,
		"REALM_NOT_FOUND": 9,
	}
)

func (x AdDomainNameValidation) Enum() *AdDomainNameValidation {
	p := new(AdDomainNameValidation)
	*p = x
	return p
}

func (x AdDomainNameValidation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AdDomainNameValidation) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_ad_proto_enumTypes[0].Descriptor()
}

func (AdDomainNameValidation) Type() protoreflect.EnumType {
	return &file_protos_ad_proto_enumTypes[0]
}

func (x AdDomainNameValidation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AdDomainNameValidation.Descriptor instead.
func (AdDomainNameValidation) EnumDescriptor() ([]byte, []int) {
	return file_protos_ad_proto_rawDescGZIP(), []int{0}
}

type CheckAdminNameResponse_AdAdminNameValidation int32

const (
	CheckAdminNameResponse_OK            CheckAdminNameResponse_AdAdminNameValidation = 0
	CheckAdminNameResponse_EMPTY         CheckAdminNameResponse_AdAdminNameValidation = 1
	CheckAdminNameResponse_INVALID_CHARS CheckAdminNameResponse_AdAdminNameValidation = 2
)

// Enum value maps for CheckAdminNameResponse_AdAdminNameValidation.
var (
	CheckAdminNameResponse_AdAdminNameValidation_name = map[int32]string{
		0: "OK",
		1: "EMPTY",
		2: "INVALID_CHARS",
	}
	CheckAdminNameResponse_AdAdminNameValidation_value = map[string]int32{
		"OK":            0,
		"EMPTY":         1,
		"INVALID_CHARS": 2,
	}
)

func (x CheckAdminNameResponse_AdAdminNameValidation) Enum() *CheckAdminNameResponse_AdAdminNameValidation {
	p := new(CheckAdminNameResponse_AdAdminNameValidation)
	*p = x
	return p
}

func (x CheckAdminNameResponse_AdAdminNameValidation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CheckAdminNameResponse_AdAdminNameValidation) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_ad_proto_enumTypes[1].Descriptor()
}

func (CheckAdminNameResponse_AdAdminNameValidation) Type() protoreflect.EnumType {
	return &file_protos_ad_proto_enumTypes[1]
}

func (x CheckAdminNameResponse_AdAdminNameValidation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CheckAdminNameResponse_AdAdminNameValidation.Descriptor instead.
func (CheckAdminNameResponse_AdAdminNameValidation) EnumDescriptor() ([]byte, []int) {
	return file_protos_ad_proto_rawDescGZIP(), []int{6, 0}
}

type CheckPasswordResponse_AdPasswordValidation int32

const (
	CheckPasswordResponse_OK    CheckPasswordResponse_AdPasswordValidation = 0
	CheckPasswordResponse_EMPTY CheckPasswordResponse_AdPasswordValidation = 1
)

// Enum value maps for CheckPasswordResponse_AdPasswordValidation.
var (
	CheckPasswordResponse_AdPasswordValidation_name = map[int32]string{
		0: "OK",
		1: "EMPTY",
	}
	CheckPasswordResponse_AdPasswordValidation_value = map[string]int32{
		"OK":    0,
		"EMPTY": 1,
	}
)

func (x CheckPasswordResponse_AdPasswordValidation) Enum() *CheckPasswordResponse_AdPasswordValidation {
	p := new(CheckPasswordResponse_AdPasswordValidation)
	*p = x
	return p
}

func (x CheckPasswordResponse_AdPasswordValidation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CheckPasswordResponse_AdPasswordValidation) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_ad_proto_enumTypes[2].Descriptor()
}

func (CheckPasswordResponse_AdPasswordValidation) Type() protoreflect.EnumType {
	return &file_protos_ad_proto_enumTypes[2]
}

func (x CheckPasswordResponse_AdPasswordValidation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CheckPasswordResponse_AdPasswordValidation.Descriptor instead.
func (CheckPasswordResponse_AdPasswordValidation) EnumDescriptor() ([]byte, []int) {
	return file_protos_ad_proto_rawDescGZIP(), []int{8, 0}
}

type GetJoinResultResponse_AdJoinResult int32

const (
	GetJoinResultResponse_OK             GetJoinResultResponse_AdJoinResult = 0
	GetJoinResultResponse_JOIN_ERROR     GetJoinResultResponse_AdJoinResult = 1
	GetJoinResultResponse_EMPTY_HOSTNAME GetJoinResultResponse_AdJoinResult = 2
	GetJoinResultResponse_PAM_ERROR      GetJoinResultResponse_AdJoinResult = 3
	GetJoinResultResponse_UNKNOWN        GetJoinResultResponse_AdJoinResult = 4
)

// Enum value maps for GetJoinResultResponse_AdJoinResult.
var (
	GetJoinResultResponse_AdJoinResult_name = map[int32]string{
		0: "OK",
		1: "JOIN_ERROR",
		2: "EMPTY_HOSTNAME",
		3: "PAM_ERROR",
		4: "UNKNOWN",
	}
	GetJoinResultResponse_AdJoinResult_value = map[string]int32{
		"OK":             0,
		"JOIN_ERROR":     1,
		"EMPTY_HOSTNAME": 2,
		"PAM_ERROR":      3,
		"UNKNOWN":        4,
	}
)

func (x GetJoinResultResponse_AdJoinResult) Enum() *GetJoinResultResponse_AdJoinResult {
	p := new(GetJoinResultResponse_AdJoinResult)
	*p = x
	return p
}

func (x GetJoinResultResponse_AdJoinResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetJoinResultResponse_AdJoinResult) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_ad_proto_enumTypes[3].Descriptor()
}

func (GetJoinResultResponse_AdJoinResult) Type() protoreflect.EnumType {
	return &file_protos_ad_proto_enumTypes[3]
}

func (x GetJoinResultResponse_AdJoinResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetJoinResultResponse_AdJoinResult.Descriptor instead.
func (GetJoinResultResponse_AdJoinResult) EnumDescriptor() ([]byte, []int) {
	return file_protos_ad_proto_rawDescGZIP(), []int{14, 0}
}

type HasSupportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasSupport    bool                   `protobuf:"varint,1,opt,name=has_support,json=hasSupport,proto3" json:"has_support,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HasSupportResponse) Reset() {
	*x = HasSupportResponse{}
	mi := &file_protos_ad_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HasSupportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasSupportResponse) ProtoMessage() {}

func (x *HasSupportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ad_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasSupportResponse.ProtoReflect.Descriptor instead.
func (*HasSupportResponse) Descriptor() ([]byte, []int) {
	return file_protos_ad_proto_rawDescGZIP(), []int{0}
}

func (x *HasSupportResponse) GetHasSupport() bool {
	if x != nil {
		return x.HasSupport
	}
	return false
}

type IsUsedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsUsed        bool                   `protobuf:"varint,1,opt,name=is_used,json=isUsed,proto3" json:"is_used,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsUsedResponse) Reset() {
	*x = IsUsedResponse{}
	mi := &file_protos_ad_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsUsedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsUsedResponse) ProtoMessage() {}

func (x *IsUsedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ad_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsUsedResponse.ProtoReflect.Descriptor instead.
func (*IsUsedResponse) Descriptor() ([]byte, []int) {
	return file_protos_ad_proto_rawDescGZIP(), []int{1}
}

func (x *IsUsedResponse) GetIsUsed() bool {
	if x != nil {
		return x.IsUsed
	}
	return false
}

type SetUsedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsUsed        bool                   `protobuf:"varint,1,opt,name=is_used,json=isUsed,proto3" json:"is_used,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetUsedRequest) Reset() {
	*x = SetUsedRequest{}
	mi := &file_protos_ad_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUsedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUsedRequest) ProtoMessage() {}

func (x *SetUsedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ad_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUsedRequest.ProtoReflect.Descriptor instead.
func (*SetUsedRequest) Descriptor() ([]byte, []int) {
	return file_protos_ad_proto_rawDescGZIP(), []int{2}
}

func (x *SetUsedRequest) GetIsUsed() bool {
	if x != nil {
		return x.IsUsed
	}
	return false
}

type GetConnectionInfoResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AdConnectionInfo *AdConnectionInfo      `protobuf:"bytes,1,opt,name=ad_connection_info,json=adConnectionInfo,proto3" json:"ad_connection_info,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetConnectionInfoResponse) Reset() {
	*x = GetConnectionInfoResponse{}
	mi := &file_protos_ad_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConnectionInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConnectionInfoResponse) ProtoMessage() {}

func (x *GetConnectionInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ad_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConnectionInfoResponse.ProtoReflect.Descriptor instead.
func (*GetConnectionInfoResponse) Descriptor() ([]byte, []int) {
	return file_protos_ad_proto_rawDescGZIP(), []int{3}
}

func (x *GetConnectionInfoResponse) GetAdConnectionInfo() *AdConnectionInfo {
	if x != nil {
		return x.AdConnectionInfo
	}
	return nil
}

type SetConnectionInfoRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AdConnectionInfo *AdConnectionInfo      `protobuf:"bytes,1,opt,name=ad_connection_info,json=adConnectionInfo,proto3" json:"ad_connection_info,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SetConnectionInfoRequest) Reset() {
	*x = SetConnectionInfoRequest{}
	mi := &file_protos_ad_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetConnectionInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetConnectionInfoRequest) ProtoMessage() {}

func (x *SetConnectionInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ad_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetConnectionInfoRequest.ProtoReflect.Descriptor instead.
func (*SetConnectionInfoRequest) Descriptor() ([]byte, []int) {
	return file_protos_ad_proto_rawDescGZIP(), []int{4}
}

func (x *SetConnectionInfoRequest) GetAdConnectionInfo() *AdConnectionInfo {
	if x != nil {
		return x.AdConnectionInfo
	}
	return nil
}

type CheckAdminNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdminName     string                 `protobuf:"bytes,1,opt,name=admin_name,json=adminName,proto3" json:"admin_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAdminNameRequest) Reset() {
	*x = CheckAdminNameRequest{}
	mi := &file_protos_ad_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAdminNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAdminNameRequest) ProtoMessage() {}

func (x *CheckAdminNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ad_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAdminNameRequest.ProtoReflect.Descriptor instead.
func (*CheckAdminNameRequest) Descriptor() ([]byte, []int) {
	return file_protos_ad_proto_rawDescGZIP(), []int{5}
}

func (x *CheckAdminNameRequest) GetAdminName() string {
	if x != nil {
		return x.AdminName
	}
	return ""
}

type CheckAdminNameResponse struct {
	state         protoimpl.MessageState                       `protogen:"open.v1"`
	Validation    CheckAdminNameResponse_AdAdminNameValidation `protobuf:"varint,1,opt,name=validation,proto3,enum=active_directory.CheckAdminNameResponse_AdAdminNameValidation" json:"validation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAdminNameResponse) Reset() {
	*x = CheckAdminNameResponse{}
	mi := &file_protos_ad_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAdminNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAdminNameResponse) ProtoMessage() {}

func (x *CheckAdminNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ad_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAdminNameResponse.ProtoReflect.Descriptor instead.
func (*CheckAdminNameResponse) Descriptor() ([]byte, []int) {
	return file_protos_ad_proto_rawDescGZIP(), []int{6}
}

func (x *CheckAdminNameResponse) GetValidation() CheckAdminNameResponse_AdAdminNameValidation {
	if x != nil {
		return x.Validation
	}
	return CheckAdminNameResponse_OK
}

type CheckPasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Password      string                 `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPasswordRequest) Reset() {
	*x = CheckPasswordRequest{}
	mi := &file_protos_ad_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPasswordRequest) ProtoMessage() {}

func (x *CheckPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ad_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPasswordRequest.ProtoReflect.Descriptor instead.
func (*CheckPasswordRequest) Descriptor() ([]byte, []int) {
	return file_protos_ad_proto_rawDescGZIP(), []int{7}
}

func (x *CheckPasswordRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type CheckPasswordResponse struct {
	state         protoimpl.MessageState                     `protogen:"open.v1"`
	Validation    CheckPasswordResponse_AdPasswordValidation `protobuf:"varint,1,opt,name=validation,proto3,enum=active_directory.CheckPasswordResponse_AdPasswordValidation" json:"validation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPasswordResponse) Reset() {
	*x = CheckPasswordResponse{}
	mi := &file_protos_ad_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPasswordResponse) ProtoMessage() {}

func (x *CheckPasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ad_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPasswordResponse.ProtoReflect.Descriptor instead.
func (*CheckPasswordResponse) Descriptor() ([]byte, []int) {
	return file_protos_ad_proto_rawDescGZIP(), []int{8}
}

func (x *CheckPasswordResponse) GetValidation() CheckPasswordResponse_AdPasswordValidation {
	if x != nil {
		return x.Validation
	}
	return CheckPasswordResponse_OK
}

type CheckDomainNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DomainName    string                 `protobuf:"bytes,1,opt,name=domain_name,json=domainName,proto3" json:"domain_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckDomainNameRequest) Reset() {
	*x = CheckDomainNameRequest{}
	mi := &file_protos_ad_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckDomainNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckDomainNameRequest) ProtoMessage() {}

func (x *CheckDomainNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ad_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckDomainNameRequest.ProtoReflect.Descriptor instead.
func (*CheckDomainNameRequest) Descriptor() ([]byte, []int) {
	return file_protos_ad_proto_rawDescGZIP(), []int{9}
}

func (x *CheckDomainNameRequest) GetDomainName() string {
	if x != nil {
		return x.DomainName
	}
	return ""
}

type CheckDomainNameResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Validation    []AdDomainNameValidation `protobuf:"varint,1,rep,packed,name=validation,proto3,enum=active_directory.AdDomainNameValidation" json:"validation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckDomainNameResponse) Reset() {
	*x = CheckDomainNameResponse{}
	mi := &file_protos_ad_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckDomainNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckDomainNameResponse) ProtoMessage() {}

func (x *CheckDomainNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ad_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckDomainNameResponse.ProtoReflect.Descriptor instead.
func (*CheckDomainNameResponse) Descriptor() ([]byte, []int) {
	return file_protos_ad_proto_rawDescGZIP(), []int{10}
}

func (x *CheckDomainNameResponse) GetValidation() []AdDomainNameValidation {
	if x != nil {
		return x.Validation
	}
	return nil
}

type PingDomainControllerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingDomainControllerRequest) Reset() {
	*x = PingDomainControllerRequest{}
	mi := &file_protos_ad_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingDomainControllerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingDomainControllerRequest) ProtoMessage() {}

func (x *PingDomainControllerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ad_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingDomainControllerRequest.ProtoReflect.Descriptor instead.
func (*PingDomainControllerRequest) Descriptor() ([]byte, []int) {
	return file_protos_ad_proto_rawDescGZIP(), []int{11}
}

func (x *PingDomainControllerRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type PingDomainControllerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Validation    AdDomainNameValidation `protobuf:"varint,1,opt,name=validation,proto3,enum=active_directory.AdDomainNameValidation" json:"validation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingDomainControllerResponse) Reset() {
	*x = PingDomainControllerResponse{}
	mi := &file_protos_ad_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingDomainControllerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingDomainControllerResponse) ProtoMessage() {}

func (x *PingDomainControllerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ad_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingDomainControllerResponse.ProtoReflect.Descriptor instead.
func (*PingDomainControllerResponse) Descriptor() ([]byte, []int) {
	return file_protos_ad_proto_rawDescGZIP(), []int{12}
}

func (x *PingDomainControllerResponse) GetValidation() AdDomainNameValidation {
	if x != nil {
		return x.Validation
	}
	return AdDomainNameValidation_OK
}

type GetJoinResultRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AdConnectionInfo *AdConnectionInfo      `protobuf:"bytes,1,opt,name=ad_connection_info,json=adConnectionInfo,proto3" json:"ad_connection_info,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetJoinResultRequest) Reset() {
	*x = GetJoinResultRequest{}
	mi := &file_protos_ad_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJoinResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJoinResultRequest) ProtoMessage() {}

func (x *GetJoinResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ad_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJoinResultRequest.ProtoReflect.Descriptor instead.
func (*GetJoinResultRequest) Descriptor() ([]byte, []int) {
	return file_protos_ad_proto_rawDescGZIP(), []int{13}
}

func (x *GetJoinResultRequest) GetAdConnectionInfo() *AdConnectionInfo {
	if x != nil {
		return x.AdConnectionInfo
	}
	return nil
}

type GetJoinResultResponse struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	JoinResult    GetJoinResultResponse_AdJoinResult `protobuf:"varint,1,opt,name=join_result,json=joinResult,proto3,enum=active_directory.GetJoinResultResponse_AdJoinResult" json:"join_result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJoinResultResponse) Reset() {
	*x = GetJoinResultResponse{}
	mi := &file_protos_ad_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJoinResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJoinResultResponse) ProtoMessage() {}

func (x *GetJoinResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ad_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJoinResultResponse.ProtoReflect.Descriptor instead.
func (*GetJoinResultResponse) Descriptor() ([]byte, []int) {
	return file_protos_ad_proto_rawDescGZIP(), []int{14}
}

func (x *GetJoinResultResponse) GetJoinResult() GetJoinResultResponse_AdJoinResult {
	if x != nil {
		return x.JoinResult
	}
	return GetJoinResultResponse_OK
}

type AdConnectionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DomainName    string                 `protobuf:"bytes,1,opt,name=domain_name,json=domainName,proto3" json:"domain_name,omitempty"`
	AdminName     string                 `protobuf:"bytes,2,opt,name=admin_name,json=adminName,proto3" json:"admin_name,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdConnectionInfo) Reset() {
	*x = AdConnectionInfo{}
	mi := &file_protos_ad_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdConnectionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdConnectionInfo) ProtoMessage() {}

func (x *AdConnectionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ad_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdConnectionInfo.ProtoReflect.Descriptor instead.
func (*AdConnectionInfo) Descriptor() ([]byte, []int) {
	return file_protos_ad_proto_rawDescGZIP(), []int{15}
}

func (x *AdConnectionInfo) GetDomainName() string {
	if x != nil {
		return x.DomainName
	}
	return ""
}

func (x *AdConnectionInfo) GetAdminName() string {
	if x != nil {
		return x.AdminName
	}
	return ""
}

func (x *AdConnectionInfo) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

var File_protos_ad_proto protoreflect.FileDescriptor

const file_protos_ad_proto_rawDesc = "" +
	"\n" +
	"\x0fprotos/ad.proto\x12\x10active_directory\x1a\x1bgoogle/protobuf/empty.proto\"5\n" +
	"\x12HasSupportResponse\x12\x1f\n" +
	"\vhas_support\x18\x01 \x01(\bR\n" +
	"hasSupport\")\n" +
	"\x0eIsUsedResponse\x12\x17\n" +
	"\ais_used\x18\x01 \x01(\bR\x06isUsed\")\n" +
	"\x0eSetUsedRequest\x12\x17\n" +
	"\ais_used\x18\x01 \x01(\bR\x06isUsed\"m\n" +
	"\x19GetConnectionInfoResponse\x12P\n" +
	"\x12ad_connection_info\x18\x01 \x01(\v2\".active_directory.AdConnectionInfoR\x10adConnectionInfo\"l\n" +
	"\x18SetConnectionInfoRequest\x12P\n" +
	"\x12ad_connection_info\x18\x01 \x01(\v2\".active_directory.AdConnectionInfoR\x10adConnectionInfo\"6\n" +
	"\x15CheckAdminNameRequest\x12\x1d\n" +
	"\n" +
	"admin_name\x18\x01 \x01(\tR\tadminName\"\xb7\x01\n" +
	"\x16CheckAdminNameResponse\x12^\n" +
	"\n" +
	"validation\x18\x01 \x01(\x0e2>.active_directory.CheckAdminNameResponse.AdAdminNameValidationR\n" +
	"validation\"=\n" +
	"\x15AdAdminNameValidation\x12\x06\n" +
	"\x02OK\x10\x00\x12\t\n" +
	"\x05EMPTY\x10\x01\x12\x11\n" +
	"\rINVALID_CHARS\x10\x02\"2\n" +
	"\x14CheckPasswordRequest\x12\x1a\n" +
	"\bpassword\x18\x01 \x01(\tR\bpassword\"\xa0\x01\n" +
	"\x15CheckPasswordResponse\x12\\\n" +
	"\n" +
	"validation\x18\x01 \x01(\x0e2<.active_directory.CheckPasswordResponse.AdPasswordValidationR\n" +
	"validation\")\n" +
	"\x14AdPasswordValidation\x12\x06\n" +
	"\x02OK\x10\x00\x12\t\n" +
	"\x05EMPTY\x10\x01\"9\n" +
	"\x16CheckDomainNameRequest\x12\x1f\n" +
	"\vdomain_name\x18\x01 \x01(\tR\n" +
	"domainName\"c\n" +
	"\x17CheckDomainNameResponse\x12H\n" +
	"\n" +
	"validation\x18\x01 \x03(\x0e2(.active_directory.AdDomainNameValidationR\n" +
	"validation\"5\n" +
	"\x1bPingDomainControllerRequest\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\"h\n" +
	"\x1cPingDomainControllerResponse\x12H\n" +
	"\n" +
	"validation\x18\x01 \x01(\x0e2(.active_directory.AdDomainNameValidationR\n" +
	"validation\"h\n" +
	"\x14GetJoinResultRequest\x12P\n" +
	"\x12ad_connection_info\x18\x01 \x01(\v2\".active_directory.AdConnectionInfoR\x10adConnectionInfo\"\xc6\x01\n" +
	"\x15GetJoinResultResponse\x12U\n" +
	"\vjoin_result\x18\x01 \x01(\x0e24.active_directory.GetJoinResultResponse.AdJoinResultR\n" +
	"joinResult\"V\n" +
	"\fAdJoinResult\x12\x06\n" +
	"\x02OK\x10\x00\x12\x0e\n" +
	"\n" +
	"JOIN_ERROR\x10\x01\x12\x12\n" +
	"\x0eEMPTY_HOSTNAME\x10\x02\x12\r\n" +
	"\tPAM_ERROR\x10\x03\x12\v\n" +
	"\aUNKNOWN\x10\x04\"n\n" +
	"\x10AdConnectionInfo\x12\x1f\n" +
	"\vdomain_name\x18\x01 \x01(\tR\n" +
	"domainName\x12\x1d\n" +
	"\n" +
	"admin_name\x18\x02 \x01(\tR\tadminName\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword*\xb2\x01\n" +
	"\x16AdDomainNameValidation\x12\x06\n" +
	"\x02OK\x10\x00\x12\t\n" +
	"\x05EMPTY\x10\x01\x12\f\n" +
	"\bTOO_LONG\x10\x02\x12\x11\n" +
	"\rINVALID_CHARS\x10\x03\x12\r\n" +
	"\tSTART_DOT\x10\x04\x12\v\n" +
	"\aEND_DOT\x10\x05\x12\x10\n" +
	"\fSTART_HYPHEN\x10\x06\x12\x0e\n" +
	"\n" +
	"END_HYPHEN\x10\a\x12\x11\n" +
	"\rMULTIPLE_DOTS\x10\b\x12\x13\n" +
	"\x0fREALM_NOT_FOUND\x10\t2\xa8\a\n" +
	"\x16ActiveDirectoryService\x12J\n" +
	"\n" +
	"HasSupport\x12\x16.google.protobuf.Empty\x1a$.active_directory.HasSupportResponse\x12B\n" +
	"\x06IsUsed\x12\x16.google.protobuf.Empty\x1a .active_directory.IsUsedResponse\x12C\n" +
	"\aSetUsed\x12 .active_directory.SetUsedRequest\x1a\x16.google.protobuf.Empty\x12X\n" +
	"\x11GetConnectionInfo\x12\x16.google.protobuf.Empty\x1a+.active_directory.GetConnectionInfoResponse\x12W\n" +
	"\x11SetConnectionInfo\x12*.active_directory.SetConnectionInfoRequest\x1a\x16.google.protobuf.Empty\x12f\n" +
	"\x0fCheckDomainName\x12(.active_directory.CheckDomainNameRequest\x1a).active_directory.CheckDomainNameResponse\x12c\n" +
	"\x0eCheckAdminName\x12'.active_directory.CheckAdminNameRequest\x1a(.active_directory.CheckAdminNameResponse\x12`\n" +
	"\rCheckPassword\x12&.active_directory.CheckPasswordRequest\x1a'.active_directory.CheckPasswordResponse\x12u\n" +
	"\x14PingDomainController\x12-.active_directory.PingDomainControllerRequest\x1a..active_directory.PingDomainControllerResponse\x12`\n" +
	"\rGetJoinResult\x12&.active_directory.GetJoinResultRequest\x1a'.active_directory.GetJoinResultResponseB;Z9github.com/canonical/ubuntu-desktop-provision/provd/protob\x06proto3"

var (
	file_protos_ad_proto_rawDescOnce sync.Once
	file_protos_ad_proto_rawDescData []byte
)

func file_protos_ad_proto_rawDescGZIP() []byte {
	file_protos_ad_proto_rawDescOnce.Do(func() {
		file_protos_ad_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_ad_proto_rawDesc), len(file_protos_ad_proto_rawDesc)))
	})
	return file_protos_ad_proto_rawDescData
}

var file_protos_ad_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_protos_ad_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_protos_ad_proto_goTypes = []any{
	(AdDomainNameValidation)(0),                       // 0: active_directory.AdDomainNameValidation
	(CheckAdminNameResponse_AdAdminNameValidation)(0), // 1: active_directory.CheckAdminNameResponse.AdAdminNameValidation
	(CheckPasswordResponse_AdPasswordValidation)(0),   // 2: active_directory.CheckPasswordResponse.AdPasswordValidation
	(GetJoinResultResponse_AdJoinResult)(0),           // 3: active_directory.GetJoinResultResponse.AdJoinResult
	(*HasSupportResponse)(nil),                        // 4: active_directory.HasSupportResponse
	(*IsUsedResponse)(nil),                            // 5: active_directory.IsUsedResponse
	(*SetUsedRequest)(nil),                            // 6: active_directory.SetUsedRequest
	(*GetConnectionInfoResponse)(nil),                 // 7: active_directory.GetConnectionInfoResponse
	(*SetConnectionInfoRequest)(nil),                  // 8: active_directory.SetConnectionInfoRequest
	(*CheckAdminNameRequest)(nil),                     // 9: active_directory.CheckAdminNameRequest
	(*CheckAdminNameResponse)(nil),                    // 10: active_directory.CheckAdminNameResponse
	(*CheckPasswordRequest)(nil),                      // 11: active_directory.CheckPasswordRequest
	(*CheckPasswordResponse)(nil),                     // 12: active_directory.CheckPasswordResponse
	(*CheckDomainNameRequest)(nil),                    // 13: active_directory.CheckDomainNameRequest
	(*CheckDomainNameResponse)(nil),                   // 14: active_directory.CheckDomainNameResponse
	(*PingDomainControllerRequest)(nil),               // 15: active_directory.PingDomainControllerRequest
	(*PingDomainControllerResponse)(nil),              // 16: active_directory.PingDomainControllerResponse
	(*GetJoinResultRequest)(nil),                      // 17: active_directory.GetJoinResultRequest
	(*GetJoinResultResponse)(nil),                     // 18: active_directory.GetJoinResultResponse
	(*AdConnectionInfo)(nil),                          // 19: active_directory.AdConnectionInfo
	(*emptypb.Empty)(nil),                             // 20: google.protobuf.Empty
}
var file_protos_ad_proto_depIdxs = []int32{
	19, // 0: active_directory.GetConnectionInfoResponse.ad_connection_info:type_name -> active_directory.AdConnectionInfo
	19, // 1: active_directory.SetConnectionInfoRequest.ad_connection_info:type_name -> active_directory.AdConnectionInfo
	1,  // 2: active_directory.CheckAdminNameResponse.validation:type_name -> active_directory.CheckAdminNameResponse.AdAdminNameValidation
	2,  // 3: active_directory.CheckPasswordResponse.validation:type_name -> active_directory.CheckPasswordResponse.AdPasswordValidation
	0,  // 4: active_directory.CheckDomainNameResponse.validation:type_name -> active_directory.AdDomainNameValidation
	0,  // 5: active_directory.PingDomainControllerResponse.validation:type_name -> active_directory.AdDomainNameValidation
	19, // 6: active_directory.GetJoinResultRequest.ad_connection_info:type_name -> active_directory.AdConnectionInfo
	3,  // 7: active_directory.GetJoinResultResponse.join_result:type_name -> active_directory.GetJoinResultResponse.AdJoinResult
	20, // 8: active_directory.ActiveDirectoryService.HasSupport:input_type -> google.protobuf.Empty
	20, // 9: active_directory.ActiveDirectoryService.IsUsed:input_type -> google.protobuf.Empty
	6,  // 10: active_directory.ActiveDirectoryService.SetUsed:input_type -> active_directory.SetUsedRequest
	20, // 11: active_directory.ActiveDirectoryService.GetConnectionInfo:input_type -> google.protobuf.Empty
	8,  // 12: active_directory.ActiveDirectoryService.SetConnectionInfo:input_type -> active_directory.SetConnectionInfoRequest
	13, // 13: active_directory.ActiveDirectoryService.CheckDomainName:input_type -> active_directory.CheckDomainNameRequest
	9,  // 14: active_directory.ActiveDirectoryService.CheckAdminName:input_type -> active_directory.CheckAdminNameRequest
	11, // 15: active_directory.ActiveDirectoryService.CheckPassword:input_type -> active_directory.CheckPasswordRequest
	15, // 16: active_directory.ActiveDirectoryService.PingDomainController:input_type -> active_directory.PingDomainControllerRequest
	17, // 17: active_directory.ActiveDirectoryService.GetJoinResult:input_type -> active_directory.GetJoinResultRequest
	4,  // 18: active_directory.ActiveDirectoryService.HasSupport:output_type -> active_directory.HasSupportResponse
	5,  // 19: active_directory.ActiveDirectoryService.IsUsed:output_type -> active_directory.IsUsedResponse
	20, // 20: active_directory.ActiveDirectoryService.SetUsed:output_type -> google.protobuf.Empty
	7,  // 21: active_directory.ActiveDirectoryService.GetConnectionInfo:output_type -> active_directory.GetConnectionInfoResponse
	20, // 22: active_directory.ActiveDirectoryService.SetConnectionInfo:output_type -> google.protobuf.Empty
	14, // 23: active_directory.ActiveDirectoryService.CheckDomainName:output_type -> active_directory.CheckDomainNameResponse
	10, // 24: active_directory.ActiveDirectoryService.CheckAdminName:output_type -> active_directory.CheckAdminNameResponse
	12, // 25: active_directory.ActiveDirectoryService.CheckPassword:output_type -> active_directory.CheckPasswordResponse
	16, // 26: active_directory.ActiveDirectoryService.PingDomainController:output_type -> active_directory.PingDomainControllerResponse
	18, // 27: active_directory.ActiveDirectoryService.GetJoinResult:output_type -> active_directory.GetJoinResultResponse
	18, // [18:28] is the sub-list for method output_type
	8,  // [8:18] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_protos_ad_proto_init() }
func file_protos_ad_proto_init() {
	if File_protos_ad_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_ad_proto_rawDesc), len(file_protos_ad_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_ad_proto_goTypes,
		DependencyIndexes: file_protos_ad_proto_depIdxs,
		EnumInfos:         file_protos_ad_proto_enumTypes,
		MessageInfos:      file_protos_ad_proto_msgTypes,
	}.Build()
	File_protos_ad_proto = out.File
	file_protos_ad_proto_goTypes = nil
	file_protos_ad_proto_depIdxs = nil
}
