// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: protos/age_verification.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgeBracket int32

const (
	AgeBracket_UNKNOWN      AgeBracket = 0
	AgeBracket_UNDER_13     AgeBracket = 1
	AgeBracket_AGE_13_TO_15 AgeBracket = 2
	AgeBracket_AGE_16_TO_17 AgeBracket = 3
	AgeBracket_AGE_18_PLUS  AgeBracket = 4
)

// Enum value maps for AgeBracket.
var (
	AgeBracket_name = map[int32]string{
		0: "UNKNOWN",
		1: "UNDER_13",
		2: "AGE_13_TO_15",
		3: "AGE_16_TO_17",
		4: "AGE_18_PLUS",
	}
	AgeBracket_value = map[string]int32{
		"UNKNOWN":      0,
		"UNDER_13":     1,
		"AGE_13_TO_15": 2,
		"AGE_16_TO_17": 3,
		"AGE_18_PLUS":  4,
	}
)

func (x AgeBracket) Enum() *AgeBracket {
	p := new(AgeBracket)
	*p = x
	return p
}

func (x AgeBracket) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgeBracket) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_age_verification_proto_enumTypes[0].Descriptor()
}

func (AgeBracket) Type() protoreflect.EnumType {
	return &file_protos_age_verification_proto_enumTypes[0]
}

func (x AgeBracket) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgeBracket.Descriptor instead.
func (AgeBracket) EnumDescriptor() ([]byte, []int) {
	return file_protos_age_verification_proto_rawDescGZIP(), []int{0}
}

type SetAgeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	BirthYear     int32                  `protobuf:"varint,2,opt,name=birth_year,json=birthYear,proto3" json:"birth_year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAgeRequest) Reset() {
	*x = SetAgeRequest{}
	mi := &file_protos_age_verification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAgeRequest) ProtoMessage() {}

func (x *SetAgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_age_verification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAgeRequest.ProtoReflect.Descriptor instead.
func (*SetAgeRequest) Descriptor() ([]byte, []int) {
	return file_protos_age_verification_proto_rawDescGZIP(), []int{0}
}

func (x *SetAgeRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SetAgeRequest) GetBirthYear() int32 {
	if x != nil {
		return x.BirthYear
	}
	return 0
}

type SetAgeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAgeResponse) Reset() {
	*x = SetAgeResponse{}
	mi := &file_protos_age_verification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAgeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAgeResponse) ProtoMessage() {}

func (x *SetAgeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_age_verification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAgeResponse.ProtoReflect.Descriptor instead.
func (*SetAgeResponse) Descriptor() ([]byte, []int) {
	return file_protos_age_verification_proto_rawDescGZIP(), []int{1}
}

type GetAgeBracketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgeBracketRequest) Reset() {
	*x = GetAgeBracketRequest{}
	mi := &file_protos_age_verification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgeBracketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgeBracketRequest) ProtoMessage() {}

func (x *GetAgeBracketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_age_verification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgeBracketRequest.ProtoReflect.Descriptor instead.
func (*GetAgeBracketRequest) Descriptor() ([]byte, []int) {
	return file_protos_age_verification_proto_rawDescGZIP(), []int{2}
}

func (x *GetAgeBracketRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type GetAgeBracketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bracket       AgeBracket             `protobuf:"varint,1,opt,name=bracket,proto3,enum=age_verification.AgeBracket" json:"bracket,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgeBracketResponse) Reset() {
	*x = GetAgeBracketResponse{}
	mi := &file_protos_age_verification_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgeBracketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgeBracketResponse) ProtoMessage() {}

func (x *GetAgeBracketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_age_verification_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgeBracketResponse.ProtoReflect.Descriptor instead.
func (*GetAgeBracketResponse) Descriptor() ([]byte, []int) {
	return file_protos_age_verification_proto_rawDescGZIP(), []int{3}
}

func (x *GetAgeBracketResponse) GetBracket() AgeBracket {
	if x != nil {
		return x.Bracket
	}
	return AgeBracket_UNKNOWN
}

var File_protos_age_verification_proto protoreflect.FileDescriptor

const file_protos_age_verification_proto_rawDesc = "" +
	"\n" +
	"\x1dprotos/age_verification.proto\x12\x10age_verification\"J\n" +
	"\rSetAgeRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"birth_year\x18\x02 \x01(\x05R\tbirthYear\"\x10\n" +
	"\x0eSetAgeResponse\"2\n" +
	"\x14GetAgeBracketRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"O\n" +
	"\x15GetAgeBracketResponse\x126\n" +
	"\abracket\x18\x01 \x01(\x0e2\x1c.age_verification.AgeBracketR\abracket*\\\n" +
	"\n" +
	"AgeBracket\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\f\n" +
	"\bUNDER_13\x10\x01\x12\x10\n" +
	"\fAGE_13_TO_15\x10\x02\x12\x10\n" +
	"\fAGE_16_TO_17\x10\x03\x12\x0f\n" +
	"\vAGE_18_PLUS\x10\x042\xc0\x01\n" +
	"\x0fAgeVerification\x12K\n" +
	"\x06SetAge\x12\x1f.age_verification.SetAgeRequest\x1a .age_verification.SetAgeResponse\x12`\n" +
	"\rGetAgeBracket\x12&.age_verification.GetAgeBracketRequest\x1a'.age_verification.GetAgeBracketResponseB;Z9github.com/canonical/ubuntu-desktop-provision/provd/protob\x06proto3"

var (
	file_protos_age_verification_proto_rawDescOnce sync.Once
	file_protos_age_verification_proto_rawDescData []byte
)

func file_protos_age_verification_proto_rawDescGZIP() []byte {
	file_protos_age_verification_proto_rawDescOnce.Do(func() {
		file_protos_age_verification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_age_verification_proto_rawDesc), len(file_protos_age_verification_proto_rawDesc)))
	})
	return file_protos_age_verification_proto_rawDescData
}

var file_protos_age_verification_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protos_age_verification_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protos_age_verification_proto_goTypes = []any{
	(AgeBracket)(0),               // 0: age_verification.AgeBracket
	(*SetAgeRequest)(nil),         // 1: age_verification.SetAgeRequest
	(*SetAgeResponse)(nil),        // 2: age_verification.SetAgeResponse
	(*GetAgeBracketRequest)(nil),  // 3: age_verification.GetAgeBracketRequest
	(*GetAgeBracketResponse)(nil), // 4: age_verification.GetAgeBracketResponse
}
var file_protos_age_verification_proto_depIdxs = []int32{
	0, // 0: age_verification.GetAgeBracketResponse.bracket:type_name -> age_verification.AgeBracket
	1, // 1: age_verification.AgeVerification.SetAge:input_type -> age_verification.SetAgeRequest
	3, // 2: age_verification.AgeVerification.GetAgeBracket:input_type -> age_verification.GetAgeBracketRequest
	2, // 3: age_verification.AgeVerification.SetAge:output_type -> age_verification.SetAgeResponse
	4, // 4: age_verification.AgeVerification.GetAgeBracket:output_type -> age_verification.GetAgeBracketResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protos_age_verification_proto_init() }
func file_protos_age_verification_proto_init() {
	if File_protos_age_verification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_age_verification_proto_rawDesc), len(file_protos_age_verification_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_age_verification_proto_goTypes,
		DependencyIndexes: file_protos_age_verification_proto_depIdxs,
		EnumInfos:         file_protos_age_verification_proto_enumTypes,
		MessageInfos:      file_protos_age_verification_proto_msgTypes,
	}.Build()
	File_protos_age_verification_proto = out.File
	file_protos_age_verification_proto_goTypes = nil
	file_protos_age_verification_proto_depIdxs = nil
}
