// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.2
// source: protos/chown.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChownResponse_ChownResponseCode int32

const (
	ChownResponse_SUCCESS       ChownResponse_ChownResponseCode = 0
	ChownResponse_UNKNOWN_ERROR ChownResponse_ChownResponseCode = 1
)

// Enum value maps for ChownResponse_ChownResponseCode.
var (
	ChownResponse_ChownResponseCode_name = map[int32]string{
		0: "SUCCESS",
		1: "UNKNOWN_ERROR",
	}
	ChownResponse_ChownResponseCode_value = map[string]int32{
		"SUCCESS":       0,
		"UNKNOWN_ERROR": 1,
	}
)

func (x ChownResponse_ChownResponseCode) Enum() *ChownResponse_ChownResponseCode {
	p := new(ChownResponse_ChownResponseCode)
	*p = x
	return p
}

func (x ChownResponse_ChownResponseCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChownResponse_ChownResponseCode) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_chown_proto_enumTypes[0].Descriptor()
}

func (ChownResponse_ChownResponseCode) Type() protoreflect.EnumType {
	return &file_protos_chown_proto_enumTypes[0]
}

func (x ChownResponse_ChownResponseCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChownResponse_ChownResponseCode.Descriptor instead.
func (ChownResponse_ChownResponseCode) EnumDescriptor() ([]byte, []int) {
	return file_protos_chown_proto_rawDescGZIP(), []int{1, 0}
}

type ChownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChownRequest) Reset() {
	*x = ChownRequest{}
	mi := &file_protos_chown_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChownRequest) ProtoMessage() {}

func (x *ChownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_chown_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChownRequest.ProtoReflect.Descriptor instead.
func (*ChownRequest) Descriptor() ([]byte, []int) {
	return file_protos_chown_proto_rawDescGZIP(), []int{0}
}

func (x *ChownRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type ChownResponse struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Code          ChownResponse_ChownResponseCode `protobuf:"varint,1,opt,name=code,proto3,enum=chown.ChownResponse_ChownResponseCode" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChownResponse) Reset() {
	*x = ChownResponse{}
	mi := &file_protos_chown_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChownResponse) ProtoMessage() {}

func (x *ChownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_chown_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChownResponse.ProtoReflect.Descriptor instead.
func (*ChownResponse) Descriptor() ([]byte, []int) {
	return file_protos_chown_proto_rawDescGZIP(), []int{1}
}

func (x *ChownResponse) GetCode() ChownResponse_ChownResponseCode {
	if x != nil {
		return x.Code
	}
	return ChownResponse_SUCCESS
}

var File_protos_chown_proto protoreflect.FileDescriptor

const file_protos_chown_proto_rawDesc = "" +
	"\n" +
	"\x12protos/chown.proto\x12\x05chown\"*\n" +
	"\fChownRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"\x80\x01\n" +
	"\rChownResponse\x12:\n" +
	"\x04code\x18\x01 \x01(\x0e2&.chown.ChownResponse.ChownResponseCodeR\x04code\"3\n" +
	"\x11ChownResponseCode\x12\v\n" +
	"\aSUCCESS\x10\x00\x12\x11\n" +
	"\rUNKNOWN_ERROR\x10\x012J\n" +
	"\fChownService\x12:\n" +
	"\rChownSettings\x12\x13.chown.ChownRequest\x1a\x14.chown.ChownResponseB;Z9github.com/canonical/ubuntu-desktop-provision/provd/protob\x06proto3"

var (
	file_protos_chown_proto_rawDescOnce sync.Once
	file_protos_chown_proto_rawDescData []byte
)

func file_protos_chown_proto_rawDescGZIP() []byte {
	file_protos_chown_proto_rawDescOnce.Do(func() {
		file_protos_chown_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_chown_proto_rawDesc), len(file_protos_chown_proto_rawDesc)))
	})
	return file_protos_chown_proto_rawDescData
}

var file_protos_chown_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protos_chown_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_chown_proto_goTypes = []any{
	(ChownResponse_ChownResponseCode)(0), // 0: chown.ChownResponse.ChownResponseCode
	(*ChownRequest)(nil),                 // 1: chown.ChownRequest
	(*ChownResponse)(nil),                // 2: chown.ChownResponse
}
var file_protos_chown_proto_depIdxs = []int32{
	0, // 0: chown.ChownResponse.code:type_name -> chown.ChownResponse.ChownResponseCode
	1, // 1: chown.ChownService.ChownSettings:input_type -> chown.ChownRequest
	2, // 2: chown.ChownService.ChownSettings:output_type -> chown.ChownResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protos_chown_proto_init() }
func file_protos_chown_proto_init() {
	if File_protos_chown_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_chown_proto_rawDesc), len(file_protos_chown_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_chown_proto_goTypes,
		DependencyIndexes: file_protos_chown_proto_depIdxs,
		EnumInfos:         file_protos_chown_proto_enumTypes,
		MessageInfos:      file_protos_chown_proto_msgTypes,
	}.Build()
	File_protos_chown_proto = out.File
	file_protos_chown_proto_goTypes = nil
	file_protos_chown_proto_depIdxs = nil
}
