// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.2
// source: protos/gdm.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GdmService_LaunchDesktopSession_FullMethodName = "/gdm.GdmService/LaunchDesktopSession"
)

// GdmServiceClient is the client API for GdmService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GdmServiceClient interface {
	LaunchDesktopSession(ctx context.Context, in *GdmServiceRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type gdmServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGdmServiceClient(cc grpc.ClientConnInterface) GdmServiceClient {
	return &gdmServiceClient{cc}
}

func (c *gdmServiceClient) LaunchDesktopSession(ctx context.Context, in *GdmServiceRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, GdmService_LaunchDesktopSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GdmServiceServer is the server API for GdmService service.
// All implementations must embed UnimplementedGdmServiceServer
// for forward compatibility.
type GdmServiceServer interface {
	LaunchDesktopSession(context.Context, *GdmServiceRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedGdmServiceServer()
}

// UnimplementedGdmServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGdmServiceServer struct{}

func (UnimplementedGdmServiceServer) LaunchDesktopSession(context.Context, *GdmServiceRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LaunchDesktopSession not implemented")
}
func (UnimplementedGdmServiceServer) mustEmbedUnimplementedGdmServiceServer() {}
func (UnimplementedGdmServiceServer) testEmbeddedByValue()                    {}

// UnsafeGdmServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GdmServiceServer will
// result in compilation errors.
type UnsafeGdmServiceServer interface {
	mustEmbedUnimplementedGdmServiceServer()
}

func RegisterGdmServiceServer(s grpc.ServiceRegistrar, srv GdmServiceServer) {
	// If the following call pancis, it indicates UnimplementedGdmServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GdmService_ServiceDesc, srv)
}

func _GdmService_LaunchDesktopSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GdmServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GdmServiceServer).LaunchDesktopSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GdmService_LaunchDesktopSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GdmServiceServer).LaunchDesktopSession(ctx, req.(*GdmServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GdmService_ServiceDesc is the grpc.ServiceDesc for GdmService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GdmService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gdm.GdmService",
	HandlerType: (*GdmServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LaunchDesktopSession",
			Handler:    _GdmService_LaunchDesktopSession_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/gdm.proto",
}
