// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: protos/keyboard.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KeyboardSettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Layout        string                 `protobuf:"bytes,1,opt,name=layout,proto3" json:"layout,omitempty"`
	Variant       string                 `protobuf:"bytes,2,opt,name=variant,proto3" json:"variant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyboardSettings) Reset() {
	*x = KeyboardSettings{}
	mi := &file_protos_keyboard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyboardSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyboardSettings) ProtoMessage() {}

func (x *KeyboardSettings) ProtoReflect() protoreflect.Message {
	mi := &file_protos_keyboard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyboardSettings.ProtoReflect.Descriptor instead.
func (*KeyboardSettings) Descriptor() ([]byte, []int) {
	return file_protos_keyboard_proto_rawDescGZIP(), []int{0}
}

func (x *KeyboardSettings) GetLayout() string {
	if x != nil {
		return x.Layout
	}
	return ""
}

func (x *KeyboardSettings) GetVariant() string {
	if x != nil {
		return x.Variant
	}
	return ""
}

type SetKeyboardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settings      *KeyboardSettings      `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetKeyboardRequest) Reset() {
	*x = SetKeyboardRequest{}
	mi := &file_protos_keyboard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetKeyboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetKeyboardRequest) ProtoMessage() {}

func (x *SetKeyboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_keyboard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetKeyboardRequest.ProtoReflect.Descriptor instead.
func (*SetKeyboardRequest) Descriptor() ([]byte, []int) {
	return file_protos_keyboard_proto_rawDescGZIP(), []int{1}
}

func (x *SetKeyboardRequest) GetSettings() *KeyboardSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

type SetInputSourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settings      *KeyboardSettings      `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetInputSourceRequest) Reset() {
	*x = SetInputSourceRequest{}
	mi := &file_protos_keyboard_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetInputSourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetInputSourceRequest) ProtoMessage() {}

func (x *SetInputSourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_keyboard_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetInputSourceRequest.ProtoReflect.Descriptor instead.
func (*SetInputSourceRequest) Descriptor() ([]byte, []int) {
	return file_protos_keyboard_proto_rawDescGZIP(), []int{2}
}

func (x *SetInputSourceRequest) GetSettings() *KeyboardSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

type GetKeyboardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Setup         *KeyboardSetup         `protobuf:"bytes,1,opt,name=setup,proto3" json:"setup,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKeyboardResponse) Reset() {
	*x = GetKeyboardResponse{}
	mi := &file_protos_keyboard_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeyboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeyboardResponse) ProtoMessage() {}

func (x *GetKeyboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_keyboard_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeyboardResponse.ProtoReflect.Descriptor instead.
func (*GetKeyboardResponse) Descriptor() ([]byte, []int) {
	return file_protos_keyboard_proto_rawDescGZIP(), []int{3}
}

func (x *GetKeyboardResponse) GetSetup() *KeyboardSetup {
	if x != nil {
		return x.Setup
	}
	return nil
}

type KeyboardSetup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settings      *KeyboardSettings      `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings,omitempty"`
	Layouts       []*KeyboardLayout      `protobuf:"bytes,2,rep,name=layouts,proto3" json:"layouts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyboardSetup) Reset() {
	*x = KeyboardSetup{}
	mi := &file_protos_keyboard_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyboardSetup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyboardSetup) ProtoMessage() {}

func (x *KeyboardSetup) ProtoReflect() protoreflect.Message {
	mi := &file_protos_keyboard_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyboardSetup.ProtoReflect.Descriptor instead.
func (*KeyboardSetup) Descriptor() ([]byte, []int) {
	return file_protos_keyboard_proto_rawDescGZIP(), []int{4}
}

func (x *KeyboardSetup) GetSettings() *KeyboardSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *KeyboardSetup) GetLayouts() []*KeyboardLayout {
	if x != nil {
		return x.Layouts
	}
	return nil
}

type KeyboardLayout struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Variants      []*KeyboardVariant     `protobuf:"bytes,3,rep,name=variants,proto3" json:"variants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyboardLayout) Reset() {
	*x = KeyboardLayout{}
	mi := &file_protos_keyboard_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyboardLayout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyboardLayout) ProtoMessage() {}

func (x *KeyboardLayout) ProtoReflect() protoreflect.Message {
	mi := &file_protos_keyboard_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyboardLayout.ProtoReflect.Descriptor instead.
func (*KeyboardLayout) Descriptor() ([]byte, []int) {
	return file_protos_keyboard_proto_rawDescGZIP(), []int{5}
}

func (x *KeyboardLayout) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *KeyboardLayout) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *KeyboardLayout) GetVariants() []*KeyboardVariant {
	if x != nil {
		return x.Variants
	}
	return nil
}

type KeyboardVariant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyboardVariant) Reset() {
	*x = KeyboardVariant{}
	mi := &file_protos_keyboard_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyboardVariant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyboardVariant) ProtoMessage() {}

func (x *KeyboardVariant) ProtoReflect() protoreflect.Message {
	mi := &file_protos_keyboard_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyboardVariant.ProtoReflect.Descriptor instead.
func (*KeyboardVariant) Descriptor() ([]byte, []int) {
	return file_protos_keyboard_proto_rawDescGZIP(), []int{6}
}

func (x *KeyboardVariant) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *KeyboardVariant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_protos_keyboard_proto protoreflect.FileDescriptor

const file_protos_keyboard_proto_rawDesc = "" +
	"\n" +
	"\x15protos/keyboard.proto\x12\bkeyboard\x1a\x1bgoogle/protobuf/empty.proto\"D\n" +
	"\x10KeyboardSettings\x12\x16\n" +
	"\x06layout\x18\x01 \x01(\tR\x06layout\x12\x18\n" +
	"\avariant\x18\x02 \x01(\tR\avariant\"L\n" +
	"\x12SetKeyboardRequest\x126\n" +
	"\bsettings\x18\x01 \x01(\v2\x1a.keyboard.KeyboardSettingsR\bsettings\"O\n" +
	"\x15SetInputSourceRequest\x126\n" +
	"\bsettings\x18\x01 \x01(\v2\x1a.keyboard.KeyboardSettingsR\bsettings\"D\n" +
	"\x13GetKeyboardResponse\x12-\n" +
	"\x05setup\x18\x01 \x01(\v2\x17.keyboard.KeyboardSetupR\x05setup\"{\n" +
	"\rKeyboardSetup\x126\n" +
	"\bsettings\x18\x01 \x01(\v2\x1a.keyboard.KeyboardSettingsR\bsettings\x122\n" +
	"\alayouts\x18\x02 \x03(\v2\x18.keyboard.KeyboardLayoutR\alayouts\"o\n" +
	"\x0eKeyboardLayout\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x125\n" +
	"\bvariants\x18\x03 \x03(\v2\x19.keyboard.KeyboardVariantR\bvariants\"9\n" +
	"\x0fKeyboardVariant\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name2\xed\x01\n" +
	"\x0fKeyboardService\x12E\n" +
	"\vSetKeyboard\x12\x1c.keyboard.SetKeyboardRequest\x1a\x16.google.protobuf.Empty\"\x00\x12K\n" +
	"\x0eSetInputSource\x12\x1f.keyboard.SetInputSourceRequest\x1a\x16.google.protobuf.Empty\"\x00\x12F\n" +
	"\vGetKeyboard\x12\x16.google.protobuf.Empty\x1a\x1d.keyboard.GetKeyboardResponse\"\x00B;Z9github.com/canonical/ubuntu-desktop-provision/provd/protob\x06proto3"

var (
	file_protos_keyboard_proto_rawDescOnce sync.Once
	file_protos_keyboard_proto_rawDescData []byte
)

func file_protos_keyboard_proto_rawDescGZIP() []byte {
	file_protos_keyboard_proto_rawDescOnce.Do(func() {
		file_protos_keyboard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_keyboard_proto_rawDesc), len(file_protos_keyboard_proto_rawDesc)))
	})
	return file_protos_keyboard_proto_rawDescData
}

var file_protos_keyboard_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_protos_keyboard_proto_goTypes = []any{
	(*KeyboardSettings)(nil),      // 0: keyboard.KeyboardSettings
	(*SetKeyboardRequest)(nil),    // 1: keyboard.SetKeyboardRequest
	(*SetInputSourceRequest)(nil), // 2: keyboard.SetInputSourceRequest
	(*GetKeyboardResponse)(nil),   // 3: keyboard.GetKeyboardResponse
	(*KeyboardSetup)(nil),         // 4: keyboard.KeyboardSetup
	(*KeyboardLayout)(nil),        // 5: keyboard.KeyboardLayout
	(*KeyboardVariant)(nil),       // 6: keyboard.KeyboardVariant
	(*emptypb.Empty)(nil),         // 7: google.protobuf.Empty
}
var file_protos_keyboard_proto_depIdxs = []int32{
	0, // 0: keyboard.SetKeyboardRequest.settings:type_name -> keyboard.KeyboardSettings
	0, // 1: keyboard.SetInputSourceRequest.settings:type_name -> keyboard.KeyboardSettings
	4, // 2: keyboard.GetKeyboardResponse.setup:type_name -> keyboard.KeyboardSetup
	0, // 3: keyboard.KeyboardSetup.settings:type_name -> keyboard.KeyboardSettings
	5, // 4: keyboard.KeyboardSetup.layouts:type_name -> keyboard.KeyboardLayout
	6, // 5: keyboard.KeyboardLayout.variants:type_name -> keyboard.KeyboardVariant
	1, // 6: keyboard.KeyboardService.SetKeyboard:input_type -> keyboard.SetKeyboardRequest
	2, // 7: keyboard.KeyboardService.SetInputSource:input_type -> keyboard.SetInputSourceRequest
	7, // 8: keyboard.KeyboardService.GetKeyboard:input_type -> google.protobuf.Empty
	7, // 9: keyboard.KeyboardService.SetKeyboard:output_type -> google.protobuf.Empty
	7, // 10: keyboard.KeyboardService.SetInputSource:output_type -> google.protobuf.Empty
	3, // 11: keyboard.KeyboardService.GetKeyboard:output_type -> keyboard.GetKeyboardResponse
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_protos_keyboard_proto_init() }
func file_protos_keyboard_proto_init() {
	if File_protos_keyboard_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_keyboard_proto_rawDesc), len(file_protos_keyboard_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_keyboard_proto_goTypes,
		DependencyIndexes: file_protos_keyboard_proto_depIdxs,
		MessageInfos:      file_protos_keyboard_proto_msgTypes,
	}.Build()
	File_protos_keyboard_proto = out.File
	file_protos_keyboard_proto_goTypes = nil
	file_protos_keyboard_proto_depIdxs = nil
}
