// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.20.3
// source: protos/keyboard.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KeyboardSettings struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Layout  string `protobuf:"bytes,1,opt,name=layout,proto3" json:"layout,omitempty"`
	Variant string `protobuf:"bytes,2,opt,name=variant,proto3" json:"variant,omitempty"`
}

func (x *KeyboardSettings) Reset() {
	*x = KeyboardSettings{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_keyboard_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyboardSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyboardSettings) ProtoMessage() {}

func (x *KeyboardSettings) ProtoReflect() protoreflect.Message {
	mi := &file_protos_keyboard_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyboardSettings.ProtoReflect.Descriptor instead.
func (*KeyboardSettings) Descriptor() ([]byte, []int) {
	return file_protos_keyboard_proto_rawDescGZIP(), []int{0}
}

func (x *KeyboardSettings) GetLayout() string {
	if x != nil {
		return x.Layout
	}
	return ""
}

func (x *KeyboardSettings) GetVariant() string {
	if x != nil {
		return x.Variant
	}
	return ""
}

type SetKeyboardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Settings *KeyboardSettings `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings,omitempty"`
}

func (x *SetKeyboardRequest) Reset() {
	*x = SetKeyboardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_keyboard_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetKeyboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetKeyboardRequest) ProtoMessage() {}

func (x *SetKeyboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_keyboard_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetKeyboardRequest.ProtoReflect.Descriptor instead.
func (*SetKeyboardRequest) Descriptor() ([]byte, []int) {
	return file_protos_keyboard_proto_rawDescGZIP(), []int{1}
}

func (x *SetKeyboardRequest) GetSettings() *KeyboardSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

type SetInputSourceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Settings *KeyboardSettings `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings,omitempty"`
}

func (x *SetInputSourceRequest) Reset() {
	*x = SetInputSourceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_keyboard_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetInputSourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetInputSourceRequest) ProtoMessage() {}

func (x *SetInputSourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_keyboard_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetInputSourceRequest.ProtoReflect.Descriptor instead.
func (*SetInputSourceRequest) Descriptor() ([]byte, []int) {
	return file_protos_keyboard_proto_rawDescGZIP(), []int{2}
}

func (x *SetInputSourceRequest) GetSettings() *KeyboardSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

type GetKeyboardResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Setup *KeyboardSetup `protobuf:"bytes,1,opt,name=setup,proto3" json:"setup,omitempty"`
}

func (x *GetKeyboardResponse) Reset() {
	*x = GetKeyboardResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_keyboard_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetKeyboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeyboardResponse) ProtoMessage() {}

func (x *GetKeyboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_keyboard_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeyboardResponse.ProtoReflect.Descriptor instead.
func (*GetKeyboardResponse) Descriptor() ([]byte, []int) {
	return file_protos_keyboard_proto_rawDescGZIP(), []int{3}
}

func (x *GetKeyboardResponse) GetSetup() *KeyboardSetup {
	if x != nil {
		return x.Setup
	}
	return nil
}

type KeyboardSetup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Settings *KeyboardSettings `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings,omitempty"`
	Layouts  []*KeyboardLayout `protobuf:"bytes,2,rep,name=layouts,proto3" json:"layouts,omitempty"`
}

func (x *KeyboardSetup) Reset() {
	*x = KeyboardSetup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_keyboard_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyboardSetup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyboardSetup) ProtoMessage() {}

func (x *KeyboardSetup) ProtoReflect() protoreflect.Message {
	mi := &file_protos_keyboard_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyboardSetup.ProtoReflect.Descriptor instead.
func (*KeyboardSetup) Descriptor() ([]byte, []int) {
	return file_protos_keyboard_proto_rawDescGZIP(), []int{4}
}

func (x *KeyboardSetup) GetSettings() *KeyboardSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *KeyboardSetup) GetLayouts() []*KeyboardLayout {
	if x != nil {
		return x.Layouts
	}
	return nil
}

type KeyboardLayout struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code     string             `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name     string             `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Variants []*KeyboardVariant `protobuf:"bytes,3,rep,name=variants,proto3" json:"variants,omitempty"`
}

func (x *KeyboardLayout) Reset() {
	*x = KeyboardLayout{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_keyboard_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyboardLayout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyboardLayout) ProtoMessage() {}

func (x *KeyboardLayout) ProtoReflect() protoreflect.Message {
	mi := &file_protos_keyboard_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyboardLayout.ProtoReflect.Descriptor instead.
func (*KeyboardLayout) Descriptor() ([]byte, []int) {
	return file_protos_keyboard_proto_rawDescGZIP(), []int{5}
}

func (x *KeyboardLayout) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *KeyboardLayout) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *KeyboardLayout) GetVariants() []*KeyboardVariant {
	if x != nil {
		return x.Variants
	}
	return nil
}

type KeyboardVariant struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *KeyboardVariant) Reset() {
	*x = KeyboardVariant{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_keyboard_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyboardVariant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyboardVariant) ProtoMessage() {}

func (x *KeyboardVariant) ProtoReflect() protoreflect.Message {
	mi := &file_protos_keyboard_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyboardVariant.ProtoReflect.Descriptor instead.
func (*KeyboardVariant) Descriptor() ([]byte, []int) {
	return file_protos_keyboard_proto_rawDescGZIP(), []int{6}
}

func (x *KeyboardVariant) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *KeyboardVariant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_protos_keyboard_proto protoreflect.FileDescriptor

var file_protos_keyboard_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x6b, 0x65, 0x79, 0x62, 0x6f, 0x61, 0x72,
	0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x6b, 0x65, 0x79, 0x62, 0x6f, 0x61, 0x72,
	0x64, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x44,
	0x0a, 0x10, 0x4b, 0x65, 0x79, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e,
	0x67, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x61,
	0x72, 0x69, 0x61, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x61, 0x72,
	0x69, 0x61, 0x6e, 0x74, 0x22, 0x4c, 0x0a, 0x12, 0x53, 0x65, 0x74, 0x4b, 0x65, 0x79, 0x62, 0x6f,
	0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x36, 0x0a, 0x08, 0x73, 0x65,
	0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6b,
	0x65, 0x79, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2e, 0x4b, 0x65, 0x79, 0x62, 0x6f, 0x61, 0x72, 0x64,
	0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x08, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e,
	0x67, 0x73, 0x22, 0x4f, 0x0a, 0x15, 0x53, 0x65, 0x74, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x53, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x36, 0x0a, 0x08, 0x73,
	0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x6b, 0x65, 0x79, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2e, 0x4b, 0x65, 0x79, 0x62, 0x6f, 0x61, 0x72,
	0x64, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x08, 0x73, 0x65, 0x74, 0x74, 0x69,
	0x6e, 0x67, 0x73, 0x22, 0x44, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x4b, 0x65, 0x79, 0x62, 0x6f, 0x61,
	0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x05, 0x73, 0x65,
	0x74, 0x75, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6b, 0x65, 0x79, 0x62,
	0x6f, 0x61, 0x72, 0x64, 0x2e, 0x4b, 0x65, 0x79, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x53, 0x65, 0x74,
	0x75, 0x70, 0x52, 0x05, 0x73, 0x65, 0x74, 0x75, 0x70, 0x22, 0x7b, 0x0a, 0x0d, 0x4b, 0x65, 0x79,
	0x62, 0x6f, 0x61, 0x72, 0x64, 0x53, 0x65, 0x74, 0x75, 0x70, 0x12, 0x36, 0x0a, 0x08, 0x73, 0x65,
	0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6b,
	0x65, 0x79, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2e, 0x4b, 0x65, 0x79, 0x62, 0x6f, 0x61, 0x72, 0x64,
	0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x08, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e,
	0x67, 0x73, 0x12, 0x32, 0x0a, 0x07, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6b, 0x65, 0x79, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2e, 0x4b,
	0x65, 0x79, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x52, 0x07, 0x6c,
	0x61, 0x79, 0x6f, 0x75, 0x74, 0x73, 0x22, 0x6f, 0x0a, 0x0e, 0x4b, 0x65, 0x79, 0x62, 0x6f, 0x61,
	0x72, 0x64, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x35, 0x0a, 0x08, 0x76, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6b, 0x65, 0x79, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2e, 0x4b, 0x65,
	0x79, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x56, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x52, 0x08, 0x76,
	0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x73, 0x22, 0x39, 0x0a, 0x0f, 0x4b, 0x65, 0x79, 0x62, 0x6f,
	0x61, 0x72, 0x64, 0x56, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x32, 0xed, 0x01, 0x0a, 0x0f, 0x4b, 0x65, 0x79, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x45, 0x0a, 0x0b, 0x53, 0x65, 0x74, 0x4b, 0x65, 0x79,
	0x62, 0x6f, 0x61, 0x72, 0x64, 0x12, 0x1c, 0x2e, 0x6b, 0x65, 0x79, 0x62, 0x6f, 0x61, 0x72, 0x64,
	0x2e, 0x53, 0x65, 0x74, 0x4b, 0x65, 0x79, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x4b, 0x0a,
	0x0e, 0x53, 0x65, 0x74, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12,
	0x1f, 0x2e, 0x6b, 0x65, 0x79, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2e, 0x53, 0x65, 0x74, 0x49, 0x6e,
	0x70, 0x75, 0x74, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x46, 0x0a, 0x0b, 0x47, 0x65,
	0x74, 0x4b, 0x65, 0x79, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x1a, 0x1d, 0x2e, 0x6b, 0x65, 0x79, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2e, 0x47, 0x65, 0x74,
	0x4b, 0x65, 0x79, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x42, 0x3b, 0x5a, 0x39, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x63, 0x61, 0x6e, 0x6f, 0x6e, 0x69, 0x63, 0x61, 0x6c, 0x2f, 0x75, 0x62, 0x75, 0x6e, 0x74,
	0x75, 0x2d, 0x64, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x2d, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x73,
	0x69, 0x6f, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x76, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_keyboard_proto_rawDescOnce sync.Once
	file_protos_keyboard_proto_rawDescData = file_protos_keyboard_proto_rawDesc
)

func file_protos_keyboard_proto_rawDescGZIP() []byte {
	file_protos_keyboard_proto_rawDescOnce.Do(func() {
		file_protos_keyboard_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_keyboard_proto_rawDescData)
	})
	return file_protos_keyboard_proto_rawDescData
}

var file_protos_keyboard_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_protos_keyboard_proto_goTypes = []interface{}{
	(*KeyboardSettings)(nil),      // 0: keyboard.KeyboardSettings
	(*SetKeyboardRequest)(nil),    // 1: keyboard.SetKeyboardRequest
	(*SetInputSourceRequest)(nil), // 2: keyboard.SetInputSourceRequest
	(*GetKeyboardResponse)(nil),   // 3: keyboard.GetKeyboardResponse
	(*KeyboardSetup)(nil),         // 4: keyboard.KeyboardSetup
	(*KeyboardLayout)(nil),        // 5: keyboard.KeyboardLayout
	(*KeyboardVariant)(nil),       // 6: keyboard.KeyboardVariant
	(*emptypb.Empty)(nil),         // 7: google.protobuf.Empty
}
var file_protos_keyboard_proto_depIdxs = []int32{
	0, // 0: keyboard.SetKeyboardRequest.settings:type_name -> keyboard.KeyboardSettings
	0, // 1: keyboard.SetInputSourceRequest.settings:type_name -> keyboard.KeyboardSettings
	4, // 2: keyboard.GetKeyboardResponse.setup:type_name -> keyboard.KeyboardSetup
	0, // 3: keyboard.KeyboardSetup.settings:type_name -> keyboard.KeyboardSettings
	5, // 4: keyboard.KeyboardSetup.layouts:type_name -> keyboard.KeyboardLayout
	6, // 5: keyboard.KeyboardLayout.variants:type_name -> keyboard.KeyboardVariant
	1, // 6: keyboard.KeyboardService.SetKeyboard:input_type -> keyboard.SetKeyboardRequest
	2, // 7: keyboard.KeyboardService.SetInputSource:input_type -> keyboard.SetInputSourceRequest
	7, // 8: keyboard.KeyboardService.GetKeyboard:input_type -> google.protobuf.Empty
	7, // 9: keyboard.KeyboardService.SetKeyboard:output_type -> google.protobuf.Empty
	7, // 10: keyboard.KeyboardService.SetInputSource:output_type -> google.protobuf.Empty
	3, // 11: keyboard.KeyboardService.GetKeyboard:output_type -> keyboard.GetKeyboardResponse
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_protos_keyboard_proto_init() }
func file_protos_keyboard_proto_init() {
	if File_protos_keyboard_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_keyboard_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeyboardSettings); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_keyboard_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetKeyboardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_keyboard_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetInputSourceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_keyboard_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetKeyboardResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_keyboard_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeyboardSetup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_keyboard_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeyboardLayout); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_keyboard_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeyboardVariant); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_keyboard_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_keyboard_proto_goTypes,
		DependencyIndexes: file_protos_keyboard_proto_depIdxs,
		MessageInfos:      file_protos_keyboard_proto_msgTypes,
	}.Build()
	File_protos_keyboard_proto = out.File
	file_protos_keyboard_proto_rawDesc = nil
	file_protos_keyboard_proto_goTypes = nil
	file_protos_keyboard_proto_depIdxs = nil
}
