// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v4.23.4
// source: protos/locale.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetLocaleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Locale        string                 `protobuf:"bytes,1,opt,name=locale,proto3" json:"locale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetLocaleRequest) Reset() {
	*x = SetLocaleRequest{}
	mi := &file_protos_locale_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetLocaleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLocaleRequest) ProtoMessage() {}

func (x *SetLocaleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_locale_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLocaleRequest.ProtoReflect.Descriptor instead.
func (*SetLocaleRequest) Descriptor() ([]byte, []int) {
	return file_protos_locale_proto_rawDescGZIP(), []int{0}
}

func (x *SetLocaleRequest) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

type GetLocaleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Locale        string                 `protobuf:"bytes,1,opt,name=locale,proto3" json:"locale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLocaleResponse) Reset() {
	*x = GetLocaleResponse{}
	mi := &file_protos_locale_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLocaleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLocaleResponse) ProtoMessage() {}

func (x *GetLocaleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_locale_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLocaleResponse.ProtoReflect.Descriptor instead.
func (*GetLocaleResponse) Descriptor() ([]byte, []int) {
	return file_protos_locale_proto_rawDescGZIP(), []int{1}
}

func (x *GetLocaleResponse) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

var File_protos_locale_proto protoreflect.FileDescriptor

var file_protos_locale_proto_rawDesc = string([]byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x65, 0x1a, 0x1b, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65,
	0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2a, 0x0a, 0x10, 0x53, 0x65,
	0x74, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x65, 0x22, 0x2b, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x63,
	0x61, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6c,
	0x6f, 0x63, 0x61, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6c, 0x6f, 0x63,
	0x61, 0x6c, 0x65, 0x32, 0x92, 0x01, 0x0a, 0x0d, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x65, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3f, 0x0a, 0x09, 0x53, 0x65, 0x74, 0x4c, 0x6f, 0x63, 0x61,
	0x6c, 0x65, 0x12, 0x18, 0x2e, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x65, 0x2e, 0x53, 0x65, 0x74, 0x4c,
	0x6f, 0x63, 0x61, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x63,
	0x61, 0x6c, 0x65, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x19, 0x2e, 0x6c, 0x6f,
	0x63, 0x61, 0x6c, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x3b, 0x5a, 0x39, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x61, 0x6e, 0x6f, 0x6e, 0x69, 0x63, 0x61, 0x6c,
	0x2f, 0x75, 0x62, 0x75, 0x6e, 0x74, 0x75, 0x2d, 0x64, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x2d,
	0x70, 0x72, 0x6f, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x76, 0x64, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_protos_locale_proto_rawDescOnce sync.Once
	file_protos_locale_proto_rawDescData []byte
)

func file_protos_locale_proto_rawDescGZIP() []byte {
	file_protos_locale_proto_rawDescOnce.Do(func() {
		file_protos_locale_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_locale_proto_rawDesc), len(file_protos_locale_proto_rawDesc)))
	})
	return file_protos_locale_proto_rawDescData
}

var file_protos_locale_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_locale_proto_goTypes = []any{
	(*SetLocaleRequest)(nil),  // 0: locale.SetLocaleRequest
	(*GetLocaleResponse)(nil), // 1: locale.GetLocaleResponse
	(*emptypb.Empty)(nil),     // 2: google.protobuf.Empty
}
var file_protos_locale_proto_depIdxs = []int32{
	0, // 0: locale.LocaleService.SetLocale:input_type -> locale.SetLocaleRequest
	2, // 1: locale.LocaleService.GetLocale:input_type -> google.protobuf.Empty
	2, // 2: locale.LocaleService.SetLocale:output_type -> google.protobuf.Empty
	1, // 3: locale.LocaleService.GetLocale:output_type -> locale.GetLocaleResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_locale_proto_init() }
func file_protos_locale_proto_init() {
	if File_protos_locale_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_locale_proto_rawDesc), len(file_protos_locale_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_locale_proto_goTypes,
		DependencyIndexes: file_protos_locale_proto_depIdxs,
		MessageInfos:      file_protos_locale_proto_msgTypes,
	}.Build()
	File_protos_locale_proto = out.File
	file_protos_locale_proto_goTypes = nil
	file_protos_locale_proto_depIdxs = nil
}
