// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: protos/timezone.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetTimezoneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timezone      string                 `protobuf:"bytes,1,opt,name=timezone,proto3" json:"timezone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTimezoneRequest) Reset() {
	*x = SetTimezoneRequest{}
	mi := &file_protos_timezone_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTimezoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTimezoneRequest) ProtoMessage() {}

func (x *SetTimezoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_timezone_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTimezoneRequest.ProtoReflect.Descriptor instead.
func (*SetTimezoneRequest) Descriptor() ([]byte, []int) {
	return file_protos_timezone_proto_rawDescGZIP(), []int{0}
}

func (x *SetTimezoneRequest) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

type GetTimezoneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timezone      string                 `protobuf:"bytes,1,opt,name=timezone,proto3" json:"timezone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTimezoneResponse) Reset() {
	*x = GetTimezoneResponse{}
	mi := &file_protos_timezone_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTimezoneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTimezoneResponse) ProtoMessage() {}

func (x *GetTimezoneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_timezone_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTimezoneResponse.ProtoReflect.Descriptor instead.
func (*GetTimezoneResponse) Descriptor() ([]byte, []int) {
	return file_protos_timezone_proto_rawDescGZIP(), []int{1}
}

func (x *GetTimezoneResponse) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

var File_protos_timezone_proto protoreflect.FileDescriptor

const file_protos_timezone_proto_rawDesc = "" +
	"\n" +
	"\x15protos/timezone.proto\x12\btimezone\x1a\x1bgoogle/protobuf/empty.proto\"0\n" +
	"\x12SetTimezoneRequest\x12\x1a\n" +
	"\btimezone\x18\x01 \x01(\tR\btimezone\"1\n" +
	"\x13GetTimezoneResponse\x12\x1a\n" +
	"\btimezone\x18\x01 \x01(\tR\btimezone2\xa0\x01\n" +
	"\x0fTimezoneService\x12E\n" +
	"\vSetTimezone\x12\x1c.timezone.SetTimezoneRequest\x1a\x16.google.protobuf.Empty\"\x00\x12F\n" +
	"\vGetTimezone\x12\x16.google.protobuf.Empty\x1a\x1d.timezone.GetTimezoneResponse\"\x00B;Z9github.com/canonical/ubuntu-desktop-provision/provd/protob\x06proto3"

var (
	file_protos_timezone_proto_rawDescOnce sync.Once
	file_protos_timezone_proto_rawDescData []byte
)

func file_protos_timezone_proto_rawDescGZIP() []byte {
	file_protos_timezone_proto_rawDescOnce.Do(func() {
		file_protos_timezone_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_timezone_proto_rawDesc), len(file_protos_timezone_proto_rawDesc)))
	})
	return file_protos_timezone_proto_rawDescData
}

var file_protos_timezone_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_timezone_proto_goTypes = []any{
	(*SetTimezoneRequest)(nil),  // 0: timezone.SetTimezoneRequest
	(*GetTimezoneResponse)(nil), // 1: timezone.GetTimezoneResponse
	(*emptypb.Empty)(nil),       // 2: google.protobuf.Empty
}
var file_protos_timezone_proto_depIdxs = []int32{
	0, // 0: timezone.TimezoneService.SetTimezone:input_type -> timezone.SetTimezoneRequest
	2, // 1: timezone.TimezoneService.GetTimezone:input_type -> google.protobuf.Empty
	2, // 2: timezone.TimezoneService.SetTimezone:output_type -> google.protobuf.Empty
	1, // 3: timezone.TimezoneService.GetTimezone:output_type -> timezone.GetTimezoneResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_timezone_proto_init() }
func file_protos_timezone_proto_init() {
	if File_protos_timezone_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_timezone_proto_rawDesc), len(file_protos_timezone_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_timezone_proto_goTypes,
		DependencyIndexes: file_protos_timezone_proto_depIdxs,
		MessageInfos:      file_protos_timezone_proto_msgTypes,
	}.Build()
	File_protos_timezone_proto = out.File
	file_protos_timezone_proto_goTypes = nil
	file_protos_timezone_proto_depIdxs = nil
}
