// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: protos/v2/telemetry.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CollectResponse_CollectResponseType int32

const (
	CollectResponse_SUCCESS              CollectResponse_CollectResponseType = 0
	CollectResponse_SOURCE_METRICS_ERROR CollectResponse_CollectResponseType = 1
	CollectResponse_UNKNOWN_ERROR        CollectResponse_CollectResponseType = 2
)

// Enum value maps for CollectResponse_CollectResponseType.
var (
	CollectResponse_CollectResponseType_name = map[int32]string{
		0: "SUCCESS",
		1: "SOURCE_METRICS_ERROR",
		2: "UNKNOWN_ERROR",
	}
	CollectResponse_CollectResponseType_value = map[string]int32{
		"SUCCESS":              0,
		"SOURCE_METRICS_ERROR": 1,
		"UNKNOWN_ERROR":        2,
	}
)

func (x CollectResponse_CollectResponseType) Enum() *CollectResponse_CollectResponseType {
	p := new(CollectResponse_CollectResponseType)
	*p = x
	return p
}

func (x CollectResponse_CollectResponseType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CollectResponse_CollectResponseType) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_v2_telemetry_proto_enumTypes[0].Descriptor()
}

func (CollectResponse_CollectResponseType) Type() protoreflect.EnumType {
	return &file_protos_v2_telemetry_proto_enumTypes[0]
}

func (x CollectResponse_CollectResponseType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CollectResponse_CollectResponseType.Descriptor instead.
func (CollectResponse_CollectResponseType) EnumDescriptor() ([]byte, []int) {
	return file_protos_v2_telemetry_proto_rawDescGZIP(), []int{1, 0}
}

type CollectRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SourceMetricsPath string `protobuf:"bytes,1,opt,name=sourceMetricsPath,proto3" json:"sourceMetricsPath,omitempty"`
	DryRun            bool   `protobuf:"varint,2,opt,name=dryRun,proto3" json:"dryRun,omitempty"`
}

func (x *CollectRequest) Reset() {
	*x = CollectRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_v2_telemetry_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CollectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectRequest) ProtoMessage() {}

func (x *CollectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_v2_telemetry_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectRequest.ProtoReflect.Descriptor instead.
func (*CollectRequest) Descriptor() ([]byte, []int) {
	return file_protos_v2_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *CollectRequest) GetSourceMetricsPath() string {
	if x != nil {
		return x.SourceMetricsPath
	}
	return ""
}

func (x *CollectRequest) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

type CollectResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Metrics string                              `protobuf:"bytes,1,opt,name=metrics,proto3" json:"metrics,omitempty"`
	Type    CollectResponse_CollectResponseType `protobuf:"varint,2,opt,name=type,proto3,enum=telemetry.v2.CollectResponse_CollectResponseType" json:"type,omitempty"`
}

func (x *CollectResponse) Reset() {
	*x = CollectResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_v2_telemetry_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CollectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectResponse) ProtoMessage() {}

func (x *CollectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_v2_telemetry_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectResponse.ProtoReflect.Descriptor instead.
func (*CollectResponse) Descriptor() ([]byte, []int) {
	return file_protos_v2_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *CollectResponse) GetMetrics() string {
	if x != nil {
		return x.Metrics
	}
	return ""
}

func (x *CollectResponse) GetType() CollectResponse_CollectResponseType {
	if x != nil {
		return x.Type
	}
	return CollectResponse_SUCCESS
}

type SetConsentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State bool `protobuf:"varint,1,opt,name=state,proto3" json:"state,omitempty"`
}

func (x *SetConsentRequest) Reset() {
	*x = SetConsentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_v2_telemetry_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetConsentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetConsentRequest) ProtoMessage() {}

func (x *SetConsentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_v2_telemetry_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetConsentRequest.ProtoReflect.Descriptor instead.
func (*SetConsentRequest) Descriptor() ([]byte, []int) {
	return file_protos_v2_telemetry_proto_rawDescGZIP(), []int{2}
}

func (x *SetConsentRequest) GetState() bool {
	if x != nil {
		return x.State
	}
	return false
}

var File_protos_v2_telemetry_proto protoreflect.FileDescriptor

var file_protos_v2_telemetry_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x76, 0x32, 0x2f, 0x74, 0x65, 0x6c, 0x65,
	0x6d, 0x65, 0x74, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x74, 0x65, 0x6c,
	0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x2e, 0x76, 0x32, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x56, 0x0a, 0x0e, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x11, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x50, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x11, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4d, 0x65, 0x74, 0x72, 0x69,
	0x63, 0x73, 0x50, 0x61, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x72, 0x79, 0x52, 0x75, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x64, 0x72, 0x79, 0x52, 0x75, 0x6e, 0x22, 0xc3,
	0x01, 0x0a, 0x0f, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x12, 0x45, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x31, 0x2e, 0x74, 0x65, 0x6c,
	0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x2e, 0x76, 0x32, 0x2e, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x22, 0x4f, 0x0a, 0x13, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55,
	0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x00, 0x12, 0x18, 0x0a, 0x14, 0x53, 0x4f, 0x55, 0x52, 0x43,
	0x45, 0x5f, 0x4d, 0x45, 0x54, 0x52, 0x49, 0x43, 0x53, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10,
	0x01, 0x12, 0x11, 0x0a, 0x0d, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x45, 0x52, 0x52,
	0x4f, 0x52, 0x10, 0x02, 0x22, 0x29, 0x0a, 0x11, 0x53, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x73, 0x65,
	0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x32,
	0xa1, 0x01, 0x0a, 0x10, 0x54, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x46, 0x0a, 0x07, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x12,
	0x1c, 0x2e, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x2e, 0x76, 0x32, 0x2e, 0x43,
	0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e,
	0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x2e, 0x76, 0x32, 0x2e, 0x43, 0x6f, 0x6c,
	0x6c, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x45, 0x0a, 0x0a,
	0x53, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x73, 0x65, 0x6e, 0x74, 0x12, 0x1f, 0x2e, 0x74, 0x65, 0x6c,
	0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x2e, 0x76, 0x32, 0x2e, 0x53, 0x65, 0x74, 0x43, 0x6f, 0x6e,
	0x73, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x42, 0x44, 0x5a, 0x42, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x63, 0x61, 0x6e, 0x6f, 0x6e, 0x69, 0x63, 0x61, 0x6c, 0x2f, 0x75, 0x62, 0x75, 0x6e,
	0x74, 0x75, 0x2d, 0x64, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x2d, 0x70, 0x72, 0x6f, 0x76, 0x69,
	0x73, 0x69, 0x6f, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x76, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x76, 0x32, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_protos_v2_telemetry_proto_rawDescOnce sync.Once
	file_protos_v2_telemetry_proto_rawDescData = file_protos_v2_telemetry_proto_rawDesc
)

func file_protos_v2_telemetry_proto_rawDescGZIP() []byte {
	file_protos_v2_telemetry_proto_rawDescOnce.Do(func() {
		file_protos_v2_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_v2_telemetry_proto_rawDescData)
	})
	return file_protos_v2_telemetry_proto_rawDescData
}

var file_protos_v2_telemetry_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protos_v2_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protos_v2_telemetry_proto_goTypes = []interface{}{
	(CollectResponse_CollectResponseType)(0), // 0: telemetry.v2.CollectResponse.CollectResponseType
	(*CollectRequest)(nil),                   // 1: telemetry.v2.CollectRequest
	(*CollectResponse)(nil),                  // 2: telemetry.v2.CollectResponse
	(*SetConsentRequest)(nil),                // 3: telemetry.v2.SetConsentRequest
	(*emptypb.Empty)(nil),                    // 4: google.protobuf.Empty
}
var file_protos_v2_telemetry_proto_depIdxs = []int32{
	0, // 0: telemetry.v2.CollectResponse.type:type_name -> telemetry.v2.CollectResponse.CollectResponseType
	1, // 1: telemetry.v2.TelemetryService.Collect:input_type -> telemetry.v2.CollectRequest
	3, // 2: telemetry.v2.TelemetryService.SetConsent:input_type -> telemetry.v2.SetConsentRequest
	2, // 3: telemetry.v2.TelemetryService.Collect:output_type -> telemetry.v2.CollectResponse
	4, // 4: telemetry.v2.TelemetryService.SetConsent:output_type -> google.protobuf.Empty
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protos_v2_telemetry_proto_init() }
func file_protos_v2_telemetry_proto_init() {
	if File_protos_v2_telemetry_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_v2_telemetry_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CollectRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_v2_telemetry_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CollectResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_v2_telemetry_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetConsentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_v2_telemetry_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_v2_telemetry_proto_goTypes,
		DependencyIndexes: file_protos_v2_telemetry_proto_depIdxs,
		EnumInfos:         file_protos_v2_telemetry_proto_enumTypes,
		MessageInfos:      file_protos_v2_telemetry_proto_msgTypes,
	}.Build()
	File_protos_v2_telemetry_proto = out.File
	file_protos_v2_telemetry_proto_rawDesc = nil
	file_protos_v2_telemetry_proto_goTypes = nil
	file_protos_v2_telemetry_proto_depIdxs = nil
}
