// Mocks generated by Mockito 5.4.2 from annotations
// in ubuntu_init/test/test_init.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:ubuntu_init/ubuntu_init.dart' as _i2;
import 'package:ubuntu_utils/src/url_launcher.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [PrivacyService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPrivacyService extends _i1.Mock implements _i2.PrivacyService {
  MockPrivacyService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> isLocationEnabled() => (super.noSuchMethod(
        Invocation.method(
          #isLocationEnabled,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
  @override
  _i3.Future<void> setLocationEnabled(bool? enabled) => (super.noSuchMethod(
        Invocation.method(
          #setLocationEnabled,
          [enabled],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
  @override
  _i3.Future<bool> isReportingEnabled() => (super.noSuchMethod(
        Invocation.method(
          #isReportingEnabled,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
  @override
  _i3.Future<void> setReportingEnabled(bool? enabled) => (super.noSuchMethod(
        Invocation.method(
          #setReportingEnabled,
          [enabled],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
  @override
  _i3.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [PrivilegedDesktopLauncher].
///
/// See the documentation for Mockito's code generation for more information.
class MockPrivilegedDesktopLauncher extends _i1.Mock
    implements _i2.PrivilegedDesktopLauncher {
  MockPrivilegedDesktopLauncher() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isAvailable => (super.noSuchMethod(
        Invocation.getter(#isAvailable),
        returnValue: false,
      ) as bool);
  @override
  _i3.Future<void> connect() => (super.noSuchMethod(
        Invocation.method(
          #connect,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
  @override
  _i3.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
  @override
  _i3.Future<void> openDesktopEntry(String? desktopFileId) =>
      (super.noSuchMethod(
        Invocation.method(
          #openDesktopEntry,
          [desktopFileId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [UrlLauncher].
///
/// See the documentation for Mockito's code generation for more information.
class MockUrlLauncher extends _i1.Mock implements _i4.UrlLauncher {
  MockUrlLauncher() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> launchUrl(String? url) => (super.noSuchMethod(
        Invocation.method(
          #launchUrl,
          [url],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}

/// A class which mocks [InitModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockInitModel extends _i1.Mock implements _i2.InitModel {
  MockInitModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
  @override
  bool hasRoute(String? route) => (super.noSuchMethod(
        Invocation.method(
          #hasRoute,
          [route],
        ),
        returnValue: false,
      ) as bool);
}
