name: Init

on:
  push:
    branches:
      - main
      - 'ubuntu/**'
      - 'canary-*'
  pull_request:
  workflow_dispatch:

env:
  FLUTTER_VERSION: '3.10.x'

jobs:
  integration:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{env.FLUTTER_VERSION}}
      - run: |
          sudo apt update
          sudo apt install -y clang cmake curl libgtk-3-dev ninja-build pkg-config unzip
          sudo apt install -y accountsservice dbus dbus-x11 gsettings-desktop-schemas network-manager upower xvfb
          echo "DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$UID/bus" >> $GITHUB_ENV
          echo "XDG_RUNTIME_DIR=/run/user/$UID" >> $GITHUB_ENV
          gsettings set org.gnome.desktop.interface gtk-theme 'Yaru'
      - run: |
          sudo -E xvfb-run -a -s '-screen 0 1024x768x24 +extension GLX' \
            $FLUTTER_ROOT/bin/flutter test integration_test
        working-directory: packages/ubuntu_init
